# Generated by Django 4.0.1 on 2022-02-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='access_code',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='session',
            name='command',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='session',
            name='current_screen',
            field=models.CharField(default='main_menu_first_page', max_length=200),
        ),
        migrations.AddField(
            model_name='session',
            name='msisdn',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='session',
            name='network',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='session',
            name='service_code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
