# Generated by Django 4.0.1 on 2022-02-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_session_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='command',
            field=models.CharField(default='continue', max_length=100),
        ),
    ]
