# Generated by Django 4.0.1 on 2022-02-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_customer_bvn_customer_msisdn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
