# Generated by Django 4.0.1 on 2022-02-08 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_customer_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerpin',
            name='session',
        ),
    ]
