# Generated by Django 4.0.1 on 2022-02-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_customerpin_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='has_card',
            field=models.BooleanField(default=False),
        ),
    ]
