# Generated by Django 4.0.1 on 2022-02-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_customer_has_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpin',
            name='last_pin',
            field=models.CharField(default='', max_length=100),
        ),
    ]
