# Generated by Django 4.0.1 on 2022-02-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_temporallist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporallist',
            name='account_no',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='temporallist',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='temporallist',
            name='num',
            field=models.CharField(max_length=200),
        ),
    ]
