# Generated by Django 4.0.1 on 2022-02-21 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_temporallist_account_no_and_more'),
        ('home', '0014_customerpin_change_count_customerpin_prev_pin'),
    ]

    operations = [
    ]
