# Generated by Django 4.0.2 on 2022-03-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_merge_20220221_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='access_code',
        ),
        migrations.RemoveField(
            model_name='session',
            name='command',
        ),
        migrations.AddField(
            model_name='customer',
            name='onboarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='session',
            name='service_code',
            field=models.CharField(default='*773#', max_length=100),
        ),
    ]
