# Generated by Django 4.0.2 on 2022-03-25 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_session_access_code_remove_session_command_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airtime',
            name='network',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='account_no',
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('current', 'Current'), ('fixed', 'Fixed')], default='savings', max_length=50)),
                ('account_no', models.CharField(default='', max_length=500)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customer')),
            ],
        ),
    ]
