# Generated by Django 4.0.2 on 2022-03-25 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_airtime_network_remove_customer_account_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtime',
            name='customer_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.customeraccount'),
        ),
        migrations.AddField(
            model_name='airtime',
            name='network',
            field=models.CharField(default='MTN', max_length=20),
        ),
    ]
