# Generated by Django 4.0.2 on 2022-03-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_airtime_customer_account_airtime_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtime',
            name='beneficiary',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
