# Generated by Django 4.0.2 on 2022-03-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_customerotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerotp',
            name='otp',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
