# Generated by Django 4.0.2 on 2022-04-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_customerotp_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='position',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
