# Generated by Django 4.0.2 on 2022-03-29 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_fundtransfer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_type', models.CharField(choices=[('self', 'Self'), ('others', 'Others')], default='self', max_length=20)),
                ('amount', models.FloatField(default=0.0, max_length=20)),
                ('beneficiary', models.CharField(blank=True, max_length=20, null=True)),
                ('network', models.CharField(default='MTN', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.customer')),
                ('customer_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.customeraccount')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.session')),
            ],
        ),
    ]
