# Generated by Django 4.0.2 on 2022-04-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_customeraccount_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='request_transaction',
            field=models.BooleanField(default=False),
        ),
    ]
