# Generated by Django 4.0.2 on 2022-04-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': 'Data', 'verbose_name_plural': 'Data'},
        ),
        migrations.AddField(
            model_name='airtime',
            name='transaction_ref',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cablesubscription',
            name='transaction_ref',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='transaction_ref',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='electricity',
            name='transaction_ref',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fundtransfer',
            name='transaction_ref',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
