# Generated by Django 4.0.2 on 2022-04-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_customeraccount_request_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='beneficiaries',
            field=models.ManyToManyField(blank=True, null=True, to='home.Beneficiary'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bvn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='card',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='recovery_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customerpin',
            name='last_pin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customerpin',
            name='prev_pin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
