# Generated by Django 4.0.2 on 2022-04-04 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_data_options_airtime_transaction_ref_and_more'),
        ('home', '0023_alter_customer_beneficiaries_alter_customer_bvn_and_more'),
    ]

    operations = [
    ]
