# Generated by Django 4.0.3 on 2022-04-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_customer_beneficiaries_alter_customer_bvn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='card',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='has_card',
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='card',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='has_card',
            field=models.BooleanField(default=False),
        ),
    ]
