# Generated by Django 4.0.3 on 2022-04-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_customer_card_remove_customer_has_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='beneficiaries',
            field=models.ManyToManyField(blank=True, to='home.beneficiary'),
        ),
        migrations.AlterField(
            model_name='customerotp',
            name='otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
