# Generated by Django 4.0.3 on 2022-04-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_customeraccount_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='request_block',
            field=models.BooleanField(default=False),
        ),
    ]
