# Generated by Django 4.0.3 on 2022-05-31 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_customer_beneficiaries'),
        ('home', '0027_customeraccount_request_block'),
    ]

    operations = [
    ]
