# Generated by Django 4.0.3 on 2022-06-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_merge_20220531_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='package',
        ),
        migrations.RemoveField(
            model_name='cablesubscription',
            name='package',
        ),
        migrations.RemoveField(
            model_name='cablesubscription',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='electricity',
            name='provider',
        ),
        migrations.AddField(
            model_name='customer',
            name='middle_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
    ]
