# Generated by Django 4.0.3 on 2022-06-19 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_billcategory_package_item_cablesubscription_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
    ]
