# Generated by Django 4.0.3 on 2022-06-19 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_remove_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.package'),
        ),
    ]
