# Generated by Django 4.0.3 on 2022-06-19 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_item_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='package',
        ),
    ]
