# Generated by Django 4.0.3 on 2022-06-26 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_customeraccount_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_ran', models.BooleanField(default=False)),
                ('amount', models.FloatField(default=0.0, max_length=20)),
                ('transaction_type', models.CharField(max_length=200, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.customer')),
                ('session_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.session')),
            ],
        ),
    ]
