# Generated by Django 4.0.3 on 2022-06-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_fundreversal_customer_account_fundreversal_msisdn'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundreversal',
            name='beneficiary',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
