# Generated by Django 4.0.3 on 2022-07-03 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_fundreversal_beneficiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundtransfer',
            name='customer_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.customeraccount'),
        ),
    ]
