# Generated by Django 4.0.3 on 2022-07-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_fundtransfer_customer_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundtransfer',
            name='bank_list_response',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='fundtransfer',
            name='bank_selected',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
