# Generated by Django 4.0.3 on 2022-07-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_fundtransfer_next'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundtransfer',
            name='bank',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
