# Generated by Django 4.0.3 on 2022-07-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_alter_customer_bvn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpin',
            name='last_pin',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customerpin',
            name='prev_pin',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
