# Generated by Django 4.0.3 on 2022-07-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_customer_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
