# Generated by Django 4.0.3 on 2022-07-14 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_data_data_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='biller_id',
            field=models.IntegerField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='package',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.billcategory'),
        ),
    ]
