# Generated by Django 4.0.3 on 2022-07-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_alter_item_biller_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='page',
            field=models.IntegerField(default=1),
        ),
    ]
