# Generated by Django 4.0.3 on 2022-07-14 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_item_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='page',
        ),
    ]
