# Generated by Django 4.0.3 on 2022-07-17 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_remove_item_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='request_removal',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BillTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0, max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('bill_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.billcategory')),
                ('bill_package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.package')),
                ('item_selected', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.item')),
            ],
        ),
    ]
