# Generated by Django 4.0.3 on 2022-07-17 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_customeraccount_request_removal_billtracker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillTracker',
        ),
    ]
