# Generated by Django 4.0.3 on 2022-07-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_delete_billtracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
