# Generated by Django 4.0.3 on 2022-07-20 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_package_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='position',
        ),
    ]
