# Generated by Django 4.0.3 on 2022-07-20 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_cablesubscription_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricity',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.package'),
        ),
    ]
