# Generated by Django 4.0.3 on 2022-07-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_electricity_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='cablesubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='electricity',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='cablesubscription',
            name='subscription_type',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='', max_length=20),
        ),
    ]
