# Generated by Django 4.0.3 on 2022-07-22 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_alter_cablesubscription_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='dob',
        ),
    ]
