# Generated by Django 4.0.3 on 2022-07-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_remove_customer_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dob',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
