# Generated by Django 4.1 on 2023-03-01 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_customer_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='airtime',
            name='pin_tries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cablesubscription',
            name='pin_tries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='pin_tries',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='msisdn',
            field=models.CharField(max_length=20),
        ),
    ]
