# Generated by Django 4.1 on 2023-03-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_delete_bank_fundtransfer_pin_tries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='charges',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
