# Generated by Django 4.1 on 2023-03-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_cablesubscription_next'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cablesubscription',
            name='next',
            field=models.CharField(blank=True, default='0', max_length=50, null=True),
        ),
    ]
